apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: widgets.example.com
spec:
  group: example.com
  scope: Namespaced
  names:
    kind: Widget
    plural: widgets
    singular: widget
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            status:
              type: object
              properties:
                phase:
                  type: string
            spec:
              type: object
              required:
                ["disabled"]
              properties:
                disabled:
                  type: boolean
                  default: false
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: IsDisabled
          type: boolean
          jsonPath: .spec.disabled
        - name: Current Phase
          type: string
          jsonPath: .status.phase
